# Generated by Django 2.0.1 on 2019-01-10 00:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20180914_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
