# Generated by Django 2.0.1 on 2019-02-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20190110_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='ftype',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='form',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
