# Generated by Django 2.0.1 on 2019-04-14 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20190216_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='opts',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
