# Generated by Django 2.0.1 on 2019-05-22 09:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_opts_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='tips',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
