# Generated by Django 2.2 on 2020-01-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_crequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='UUID'),
        ),
    ]
